version: '3.8'

services:
  cpp:
    build: .
    container_name: computer_science_python
    volumes:
      - ./../../scripts/python:/usr/src/app  # scripts/cppをコンテナ内の/usr/src/appにマウント
    working_dir: /usr/src/app
    tty: true           # ターミナルを確保（対話型シェル利用のため）
    stdin_open: true    # 標準入力を開いた状態に
    command: /bin/bash  # コンテナ起動時にbashシェルを起動